import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./component/layout";

export const metadata: Metadata = {
  title: "MuziNut",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="ko">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
